#!/bin/sh
### BEGIN INIT INFO
# Provides: maploader
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

dir="/mnt/data/maploader"
cmd="node maploader.js"
user="root"
